model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: models/${datamodule.dataset}/${model} # directory to save the model file
  monitor: "val_loss" # name of the logged metric which determines when model is improving
  verbose: False # verbosity mode
  save_top_k: 1 # save k best models (determined by above metric)
  mode: "min" # "max" means higher metric value is better, can be also "min"
  auto_insert_metric_name: True # when True, the checkpoints filenames will contain the metric name
  save_weights_only: False # if True, then only the model’s weights will be saved
  every_n_epochs: 1 # number of epochs between checkpoints
  save_on_train_epoch_end: False # whether to run checkpointing at the end of the training epoch or the end of validation