_target_: seed.lightning.data_module.PLDataModule
dataset: clapika2010/infotab
num_labels: 3
model_name_or_path: ${model.model_name_or_path}
processed: True
train_batch_size: 6
eval_batch_size: 6
eval_splits:
  - dev
test_splits:
  - test1
  - test2
  - test3